name: build ISO image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            auto-optimize-store = true
            keep-outputs = true
            keep-derivations = true
      - name: build installer
        run: |
          nix build --extra-experimental-features 'nix-command flakes' -j2 -L
          cp result/iso/*.iso .
      - uses: actions/upload-artifact@v4
        with:
          name: iso
          path: ./*.iso

      - uses: softprops/action-gh-release@v1
        with:
          files: ./*.iso
